version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: nti
      POSTGRES_PASSWORD: nti
      POSTGRES_DB: nti
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "t@t.ru"
      PGADMIN_DEFAULT_PASSWORD: "1"
    ports:
      - 8081:80
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379